language: nix
sudo: false
script: nix-shell shell.nix --argstr compiler $GHCATTR --command true --no-build-output && echo "=========================== env built ===========================" && nix-build shell.nix --argstr compiler $GHCATTR
cache:
  directories:
    - /nix
matrix:
    include:
        - os: linux
          dist: trusty
          compiler: ": #GHC 8.0.2"
          env: GHCATTR=ghc802
        - os: linux
          dist: trusty
          compiler: ": #GHC 7.10.3"
          env: GHCATTR=ghc7103
notifications:
    email: false
#         on_success: never
#         on_failure: change

# # Here starts the actual work to be performed for the package under test;
# # any command which exits with a non-zero exit code causes the build to fail.
# script:
#  - if [ -f configure.ac ]; then autoreconf -i; fi
#  - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
#  - cabal build   # this builds all libraries and executables (including tests/benchmarks)
#  - cabal test
#  - cabal check
#  - cabal sdist   # tests that a source-distribution can be generated
