language: nix
sudo: false
# script: nix-shell shell.nix --argstr compiler $GHCATTR --command true --no-build-output && nix-build shell.nix --argstr compiler $GHCATTR
script: nix-build shell.nix --argstr compiler $GHCATTR
matrix:
    include:
        - os: linux
          dist: trusty
          compiler: ": #GHC 8.0.2"
          env: GHCATTR=ghc802
        # - os: linux
        #   dist: trusty
        #   compiler: ": #GHC 7.10.3"
        #   env: GHCATTR=ghc7103
notifications:
    email:
        on_success: never
        on_failure: change
